"""Upload dataset to HuggingFace Hub."""

from __future__ import annotations

import logging
import os
import tempfile
from pathlib import Path

logger = logging.getLogger(__name__)


def upload_dataset(
    parquet_path: Path,
    repo_id: str,
    token: str | None = None,
) -> str:
    """Upload Parquet file to HuggingFace Hub.

    Args:
        parquet_path: Path to Parquet file
        repo_id: HuggingFace repo ID (e.g., "cortexlm/swe-forge")
        token: HF token (optional, uses HF_TOKEN env var if not provided)

    Returns:
        URL to the dataset on HuggingFace
    """
    try:
        from huggingface_hub import HfApi, create_repo
    except ImportError:
        raise ImportError(
            "huggingface_hub is required. Install with: pip install huggingface_hub"
        )

    if token is None:
        token = os.environ.get("HF_TOKEN")

    if not token:
        raise ValueError("HF_TOKEN not provided. Set HF_TOKEN env var or pass --token")

    api = HfApi(token=token)

    try:
        create_repo(repo_id, repo_type="dataset", token=token, exist_ok=True)
    except Exception:
        pass

    api.upload_file(
        path_or_fileobj=str(parquet_path),
        path_in_repo=parquet_path.name,
        repo_id=repo_id,
        repo_type="dataset",
        token=token,
    )

    readme_content = f"""---
license: mit
task_categories:
  - text-generation
tags:
  - code
  - swe-bench
  - software-engineering
---

# SWE-Forge Dataset

Automatically generated SWE-bench style tasks from GitHub PRs.

## Dataset Description

- **Total Tasks**: See parquet file
- **Format**: Parquet
- **Generated by**: [swe-forge](https://github.com/CortexLM/swe-forge)

## Fields

| Field | Description |
|-------|-------------|
| task_id | Unique identifier (owner-repo-pr_number) |
| repo_url | Git repository URL |
| base_commit | Base commit SHA |
| prompt | Natural language description of the task |
| language | Programming language |
| fail_to_pass | Tests that should pass after fix |
| patch | The patch to apply |

## Usage

```python
from datasets import load_dataset

dataset = load_dataset("{repo_id}")
```
"""

    with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
        f.write(readme_content)
        readme_path = f.name

    try:
        api.upload_file(
            path_or_fileobj=readme_path,
            path_in_repo="README.md",
            repo_id=repo_id,
            repo_type="dataset",
            token=token,
        )
    finally:
        Path(readme_path).unlink()

    url = f"https://huggingface.co/datasets/{repo_id}"
    logger.info(f"Uploaded to {url}")

    return url
