"""SWE-Forge: configurable-teacher synthetic SWE benchmark generator.

The forge package builds synthetic, 100%-verifiable software-engineering tasks.
Its LLM access goes exclusively through an env-driven LiteLLM layer; it never
imports the repository's bespoke LLM clients or response cache, and no provider
hostname or brand string is hardcoded anywhere in this package.
"""

from swe_forge.forge.config import ForgeSettings
from swe_forge.forge.models import (
    BAND_VERDICTS,
    GENERATOR_NAMES,
    ORACLE_VERDICTS,
    PANEL_TIERS,
    SUPPORTED_LANGUAGES,
    BaselineNotGreenError,
    CalibrationReport,
    Candidate,
    CandidateTarget,
    EnvImage,
    ExportGateError,
    FinalMutationEvidence,
    ForgeTask,
    GeneratedSpec,
    InstanceGrant,
    ModelError,
    ModelSolveRecord,
    OracleReport,
    OracleTestFile,
    Provenance,
    RepoSpec,
    require_green_baseline,
)
from swe_forge.forge.export import (
    BatchExportResult,
    ExportError,
    ExportRequest,
    TaskExportResult,
    assemble_forge_task,
    audit_exported_workspace,
    export_batch,
    export_dataset,
    export_forge_task,
    forge_task_id,
)
from swe_forge.forge.gold_eval import (
    EvalRun,
    GoldEvalError,
    GoldEvalReport,
    TaskGoldResult,
    evaluate_task_gold,
    parse_score,
    run_gold_eval,
)
from swe_forge.forge.oracle.pipeline import (
    GATE_ORDER,
    ExportRefusedError,
    OraclePipelineError,
    ensure_oracle_exportable,
    is_oracle_exportable,
    run_oracle_pipeline,
)
from swe_forge.forge.report import (
    BenchmarkReport,
    GoldSummary,
    ProvenanceCompletenessResult,
    ProvenanceConsistencyResult,
    ReportError,
    TaskProvenance,
    build_benchmark_report,
    check_provenance_completeness,
    check_provenance_consistency,
    write_report,
)
from swe_forge.forge.sources import (
    SourceError,
    SourceRegistry,
    UnknownRepoError,
    build_source_registry,
)

__all__ = [
    "BAND_VERDICTS",
    "GATE_ORDER",
    "GENERATOR_NAMES",
    "ORACLE_VERDICTS",
    "PANEL_TIERS",
    "SUPPORTED_LANGUAGES",
    "BaselineNotGreenError",
    "BatchExportResult",
    "BenchmarkReport",
    "CalibrationReport",
    "Candidate",
    "CandidateTarget",
    "EnvImage",
    "ExportError",
    "ExportGateError",
    "ExportRefusedError",
    "ExportRequest",
    "EvalRun",
    "ForgeSettings",
    "ForgeTask",
    "FinalMutationEvidence",
    "GeneratedSpec",
    "GoldEvalError",
    "GoldEvalReport",
    "GoldSummary",
    "InstanceGrant",
    "ModelError",
    "ModelSolveRecord",
    "OraclePipelineError",
    "OracleReport",
    "OracleTestFile",
    "Provenance",
    "ProvenanceCompletenessResult",
    "ProvenanceConsistencyResult",
    "ReportError",
    "RepoSpec",
    "SourceError",
    "SourceRegistry",
    "TaskExportResult",
    "TaskGoldResult",
    "TaskProvenance",
    "UnknownRepoError",
    "assemble_forge_task",
    "audit_exported_workspace",
    "build_benchmark_report",
    "build_source_registry",
    "check_provenance_completeness",
    "check_provenance_consistency",
    "ensure_oracle_exportable",
    "evaluate_task_gold",
    "export_batch",
    "export_dataset",
    "export_forge_task",
    "forge_task_id",
    "is_oracle_exportable",
    "parse_score",
    "require_green_baseline",
    "run_gold_eval",
    "run_oracle_pipeline",
    "write_report",
]
