"""Stage 3 oracle hardening: gates that make a task "100% verifiable".

Each gate runs in a throwaway :class:`~swe_forge.execution.sandbox.DockerSandbox`
on the candidate's :class:`~swe_forge.forge.models.EnvImage` and contributes
evidence to an :class:`~swe_forge.forge.models.OracleReport`. This package starts
with the *establish* gate (:mod:`swe_forge.forge.oracle.establish`), which owns
the reusable Docker FAIL->PASS (F2P) / PASS->PASS (P2P) execution recipe consumed
by the later gates and by calibration.
"""

from swe_forge.forge.oracle.establish import (
    DockerOracleRecipe,
    EstablishError,
    EstablishOutcome,
    HiddenTest,
    HiddenTestFile,
    HiddenTestSynthesizer,
    NullSynthesizer,
    RecipeProtocol,
    SandboxProtocol,
    SynthesisContext,
    TestRun,
    TreeState,
    build_establish_report,
    establish_oracle,
    run_establish_gate,
)
from swe_forge.forge.oracle.flakiness import (
    DEFAULT_FLAKINESS_RUNS,
    MIN_FLAKINESS_RUNS,
    REASON_FLAKY_LAST_F2P,
    REASON_FLAKY_P2P,
    FlakinessError,
    FlakinessOutcome,
    RecipeFactory,
    SingleRun,
    assess_flakiness,
    build_flakiness_report,
    reconstruct_hidden_tests,
    run_flakiness_gate,
)
from swe_forge.forge.oracle.mutation import (
    DEFAULT_KILL_THRESHOLD,
    DEFAULT_MAX_SYNTHESIS_ROUNDS,
    REASON_MUTATION_INADEQUATE,
    REASON_NO_MUTANTS,
    DockerMutationRunner,
    MutationError,
    MutationMeasurement,
    MutationOutcome,
    MutationRunner,
    MutationSynthesisContext,
    MutationTestSynthesizer,
    NullMutationSynthesizer,
    assess_mutation,
    build_mutation_report,
    reconstruct_base_tests,
    run_mutation_gate,
)
from swe_forge.forge.oracle.differential import (
    DEFAULT_MAX_STRENGTHEN_ROUNDS,
    DEFAULT_NUM_VARIANTS,
    REASON_DIFFERENTIAL_GOLD_NOT_GREEN,
    REASON_DIFFERENTIAL_SURVIVOR,
    DifferentialError,
    DifferentialOutcome,
    DifferentialRunner,
    DifferentialSynthesisContext,
    DockerDifferentialRunner,
    NullVariantGenerator,
    NullVariantSynthesizer,
    Variant,
    VariantFile,
    VariantGenerationContext,
    VariantGenerator,
    VariantScore,
    VariantStrengthSynthesizer,
    assess_differential,
    build_differential_report,
    reconstruct_suite_tests,
    run_differential_gate,
)

__all__ = [
    "DEFAULT_FLAKINESS_RUNS",
    "DEFAULT_KILL_THRESHOLD",
    "DEFAULT_MAX_STRENGTHEN_ROUNDS",
    "DEFAULT_MAX_SYNTHESIS_ROUNDS",
    "DEFAULT_NUM_VARIANTS",
    "MIN_FLAKINESS_RUNS",
    "REASON_DIFFERENTIAL_GOLD_NOT_GREEN",
    "REASON_DIFFERENTIAL_SURVIVOR",
    "REASON_FLAKY_LAST_F2P",
    "REASON_FLAKY_P2P",
    "REASON_MUTATION_INADEQUATE",
    "REASON_NO_MUTANTS",
    "DifferentialError",
    "DifferentialOutcome",
    "DifferentialRunner",
    "DifferentialSynthesisContext",
    "DockerDifferentialRunner",
    "DockerMutationRunner",
    "DockerOracleRecipe",
    "EstablishError",
    "EstablishOutcome",
    "FlakinessError",
    "FlakinessOutcome",
    "HiddenTest",
    "HiddenTestFile",
    "HiddenTestSynthesizer",
    "MutationError",
    "MutationMeasurement",
    "MutationOutcome",
    "MutationRunner",
    "MutationSynthesisContext",
    "MutationTestSynthesizer",
    "NullMutationSynthesizer",
    "NullSynthesizer",
    "NullVariantGenerator",
    "NullVariantSynthesizer",
    "RecipeFactory",
    "RecipeProtocol",
    "SandboxProtocol",
    "SingleRun",
    "SynthesisContext",
    "TestRun",
    "TreeState",
    "Variant",
    "VariantFile",
    "VariantGenerationContext",
    "VariantGenerator",
    "VariantScore",
    "VariantStrengthSynthesizer",
    "assess_differential",
    "assess_flakiness",
    "assess_mutation",
    "build_differential_report",
    "build_establish_report",
    "build_flakiness_report",
    "build_mutation_report",
    "establish_oracle",
    "reconstruct_base_tests",
    "reconstruct_hidden_tests",
    "reconstruct_suite_tests",
    "run_differential_gate",
    "run_establish_gate",
    "run_flakiness_gate",
    "run_mutation_gate",
]
