"""Source registry / allowlist for producers."""

from swe_factory.sources.allowlist import (
    ALLOWLIST,
    REMOTE_SEEDS,
    SCALE_LANGUAGES,
    TINY_GREEN,
    SeedRepo,
    allowlist_summary,
    get_seed,
    language_histogram,
    local_offline_seeds,
    remote_mine_seeds,
    scale_inventory_report,
    seeds_for_language,
    under_supply_reasons,
)
from swe_factory.sources.discover import (
    DiscoverCandidate,
    DiscoverError,
    DiscoverReject,
    DiscoverReport,
    discover_merge_range_from_git,
    discover_offline_fixture,
    is_full_sha,
    is_real_repository_url,
    require_full_sha,
    sanitize_api_candidate,
    validate_hybrid_curated,
)
from swe_factory.sources.git_mine import (
    GitMineError,
    GitMineReport,
    mine_allowlist_git_only,
    probe_oxylabs_live,
)

# Funnel / monorepo / clone cache are importable as submodules to avoid cycles:
#   swe_factory.sources.funnel, .monorepo, .clone_cache
# Re-export primary symbols for package consumers after skip_reasons is loaded.
from swe_factory.sources.github import (
    DISCOVERY_PATH_LIST_PULLS,
    DISCOVERY_PATH_SEARCH,
    DISCOVERY_PATHS,
    DictGitHubTransport,
    GitHubAuthError,
    GitHubClient,
    GitHubError,
    GitHubRateLimitError,
    build_merged_pr_search_query,
    resolve_github_token,
)
from swe_factory.sources.license_gate import (
    LicenseGateError,
    assert_permissive_license,
    classify_license,
    is_copyleft,
    is_permissive,
)
from swe_factory.sources.oxylabs import (
    ALLOWED_SOURCE,
    OxylabsAuthError,
    OxylabsClient,
    OxylabsError,
    OxylabsSourceError,
    has_oxylabs_credentials,
    resolve_oxylabs_credentials,
    scrape_github_http,
)
from swe_factory.sources.real_pr_pool import (
    DEFAULT_REAL_PR_SEED_IDS,
    RealPrPoolError,
    RealPrPoolReport,
    is_motor_or_hybrid_identity,
    mine_offline_real_pr_pool,
    mine_real_pr_pool,
    real_pr_seed_pool,
    summary_seed_pool_for_select5,
)
from swe_factory.sources.skip_reasons import (
    SKIP_MONOREPO,
    SKIP_REASON_DOCS,
    describe_skip_reason,
    document_all_skip_reasons,
    normalize_reason_code,
)

# Public alias used by architecture notes / package consumers.
OXYLABS_ALLOWED_SOURCE = ALLOWED_SOURCE

__all__ = [
    "ALLOWLIST",
    "DEFAULT_REAL_PR_SEED_IDS",
    "REMOTE_SEEDS",
    "SCALE_LANGUAGES",
    "SKIP_MONOREPO",
    "SKIP_REASON_DOCS",
    "TINY_GREEN",
    "DiscoverCandidate",
    "DiscoverError",
    "DiscoverReject",
    "DiscoverReport",
    "DISCOVERY_PATHS",
    "DISCOVERY_PATH_LIST_PULLS",
    "DISCOVERY_PATH_SEARCH",
    "DictGitHubTransport",
    "GitHubAuthError",
    "GitHubClient",
    "GitHubError",
    "GitHubRateLimitError",
    "GitMineError",
    "GitMineReport",
    "LicenseGateError",
    "OXYLABS_ALLOWED_SOURCE",
    "OxylabsAuthError",
    "OxylabsClient",
    "OxylabsError",
    "OxylabsSourceError",
    "RealPrPoolError",
    "RealPrPoolReport",
    "SeedRepo",
    "allowlist_summary",
    "assert_permissive_license",
    "build_merged_pr_search_query",
    "classify_license",
    "describe_skip_reason",
    "discover_merge_range_from_git",
    "discover_offline_fixture",
    "document_all_skip_reasons",
    "get_seed",
    "has_oxylabs_credentials",
    "is_copyleft",
    "is_full_sha",
    "is_motor_or_hybrid_identity",
    "is_permissive",
    "is_real_repository_url",
    "language_histogram",
    "local_offline_seeds",
    "mine_allowlist_git_only",
    "mine_offline_real_pr_pool",
    "mine_real_pr_pool",
    "normalize_reason_code",
    "probe_oxylabs_live",
    "real_pr_seed_pool",
    "remote_mine_seeds",
    "require_full_sha",
    "resolve_github_token",
    "resolve_oxylabs_credentials",
    "sanitize_api_candidate",
    "scale_inventory_report",
    "scrape_github_http",
    "seeds_for_language",
    "summary_seed_pool_for_select5",
    "under_supply_reasons",
    "validate_hybrid_curated",
]
